name: notification-bot

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: hongyiheng/weather-bot@v0.0.3
        with:
          webhook: ${{ secrets.WEBHOOK }}
          city_code: ${{ secrets.CITY_CODE }}
