name: notification-bot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: hongyiheng/notification-bot@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          city_code: ${{ secrets.CITY_CODE }}
